### ISSUE TITLE
Finir le développement?

### ISSUE THREAD

**Issue by demers** [dualB/plugin.video.fabriqueculturelle#1]
Bonjour,

J'aimerais savoir pourquoi ce module Fabrique Culturelle n'a pas été terminé?  Est-ce qu'il y aurait moyen de le poursuivre?

Merci.

fndemers@gmail.com

**Comment by dualB** [comment]
Bonjour! J'avais certains problèmes pour extraire les liens des streams, mais un de mes partenaires de Dépôt Québec m'a récemment aidé à débloqué le tout. Je manque juste de temps pour y travailler...

**Comment by demers** [comment]
Bonjour!  Si je peux aider...  Je veux me mettre à créer quelques modules Kodi depuis un bout de temps.  Je pensais aussi à un module pour matv.ca
Merci!

**Comment by dualB** [comment]
Je te fais signe quand il y aura une version beta à tester. J'y ai travaillé ce soir, sa fonctionne en gros, mais beaucoup de peaufinement en vue.

**Comment by demers** [comment]
Merci.  Oui, ça m'intéresse.  J'ai hâte de pouvoir utiliser.  Ça fait longtemps que je veux regarder la fabrique culturelle sur ma télé.  Je vais regarder aussi comment tu as codé ça pour faire mon propre module.  Tu m'écriras à fndemers@gmail.com  Merci.
